config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :admin do
    root "dashboards#index"

    get ":model", to: "crud#index", as: :index
    get ":model/new", to: "crud#new", as: :new
    get ":model/:id/edit", to: "crud#edit", as: :edit
    post ":model", to: "crud#create", as: :create
    patch ":model/:id", to: "crud#update", as: :update
    delete ":model/:id", to: "crud#destroy", as: :delete
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :user
  has_one_attached :avatar

  validates_presence_of :username
  validates_uniqueness_of :username

  def full_name
    [ first_name, last_name ].join " "
  end

  def avatar_url
    avatar.attached? ? url_for(avatar) : "/user.png"
  end

  def self.list_columns
    [
      { field: :id, name: :ID },
      { field: :username, name: "User Name" },
      { field: :first_name, name: "First Name" },
      { field: :last_name, name: "Last Name" }
    ]
  end

  def self.lnk_column
    :username
  end

  def self.form_fields
    {
      username: { type: :string, label: "Username", required: true },
      first_name: { type: :string, label: "First Name" },
      last_name: { type: :select, label: "Last Name" }
    }
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend

  layout "admin"
end

app/controllers/admin/crud_controller.rb
class Admin::CrudController < Admin::AdminController
  before_action :set_model
  before_action :set_record, only: %i[ edit update destroy ]

  def index
    @pagy, @records = pagy @model.all
  end

  def new
    @record = @model.new
  end

  def create
    @record = @model.new record_params

    if @record.save
      redirect_to admin_index_path(model: @model)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @record.update record_params
      redirect_to admin_index_path(model: @model_name), notice: "#{@model_name} updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def set_model
    @model_name = params[:model].classify
    @model = @model_name.constantize
  end

  def set_record
    @record = @model.find_by(params[:id])
  end

  def record_params
    permitted_fields = helpers.editable_fields_with_types(@model).keys.map(&:to_sym)
    params.require(@model_name.underscore.to_sym).permit(permitted_fields)
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::AdminController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/admin/crud_helper.rb
module Admin::CrudHelper
  def editable_fields_with_types(model)
    fields = model.columns_hash.reject { |name, _| %w[id created_at updated_at password_digest].include?(name) }
                             .transform_values(&:type)

    # Add virtual fields for password and password_confirmation if `has_secure_password` is enabled
    if model.column_names.include? "password_digest"
      fields["password"] = :string
      # fields["password_confirmation"] = :string
    end

    fields
  end

  def all_fields_with_types(model)
    model.columns_hash.reject { |name, _| %w[password_digest].include?(name) }
                             .transform_values(&:type)
  end

  def all_fields(model_class)
    model_class
  end

  # form helpers

  def determine_path(record)
    model_name = record.class.name
    record.new_record? ? admin_create_path(model: model_name) : admin_update_path(model: model_name, id: record.id)
  end

  def determine_method(record)
    record.new_record? ? :post : :patch
  end

  def input_type_for(field_type)
    case field_type
    when :string, :text
      :string
    when :integer, :decimal
      :number
    when :boolean
      :boolean
    when :datetime, :date, :time
      :datetime
    else
      :string
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def component(name, *args, **kwargs, &)
    render("#{name}_component".classify.constantize.new(*args, **kwargs), &)
  end

  def pagy_nav(pagy, id: nil, aria_label: nil, **vars)
    id = %( id="#{id}") if id
    a  = pagy_anchor(pagy, **vars)

    html = %(<nav#{id} class="flex justify-center items-center space-x-2" #{nav_aria_label(pagy, aria_label:)}>#{
               prev_a(pagy, a)})
    pagy.series(**vars).each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
      html << case item
      when Integer
                a.(item, classes: "px-3 py-1 border rounded-md text-slate-700 hover:bg-slate-100 hover:text-blue-500 #{'bg-blue-500 text-white' if item == pagy.page}")
      when String
                %(<a role="link" aria-disabled="true" aria-current="page" class="px-3 py-1 border rounded-md text-slate-700 hover:bg-slate-100 hover:text-blue-500">#{pagy.label_for(item)}</a>)
      when :gap
                # %(<a role="link" aria-disabled="true" class="px-3 py-1 text-slate-500">#{pagy_t('pagy.gap')}</a>)
                %(<span class="px-3 py-1 text-slate-500">…</span>)
      else
                raise InternalError, "expected item types in series to be Integer, String or :gap; got #{item.inspect}"
      end
    end
    html << %(#{next_a(pagy, a)}</nav>)
  end
end

app/views/admin/crud/_form.html.erb
<%= simple_form_for record, url: determine_path(record), method: determine_method(record) do |f| %>
  <% editable_fields_with_types(record.class).each do |field, field_type| %>
    <div class="mb-4">
      <%= f.input field, 
                  #as: input_type_for(field_type), 
                  label: field.humanize, 
                  input_html: { class: "block w-full border-gray-300 rounded-md shadow-sm" } %>
    </div>
  <% end %>
  <%= component "admin/simple_form/submit", f, method: determine_method(record) %>
<% end %>

app/views/admin/crud/edit.html.erb
<%= render "form", record: @record, model_name: @model_name %>

app/views/admin/crud/index.html.erb
<div class="flex mb-4 w-full justify-between">
  <div class="flex">
    <%= component "admin/ui/button", "Delete", "#", "fa-solid fa-trash", variant: :danger %>
  </div>
  <div class="flex">
    <%= component "admin/ui/button", "Create", admin_new_path(model: @model_name), "fa-solid fa-plus" %>
  </div>
</div>

<div class="rounded-t-lg bg-violet-50 overflow-hidden" data-controller="admin--table-resize" data-admin--table-resize-storage-key-value="user-table-sizes">
  <table class="min-w-full table-auto border-collapse border border-violet-600">
    <thead class="bg-violet-100">
      <tr>
        <% all_fields_with_types(@model).each do |field, field_type| %>
        <th class="border px-4 py-3 relative text-start text-violet-950" data-column-id="<%= field %>">
          <%= field.humanize %>
          <div data-action="mousedown->admin--table-resize#startResize" class="absolute right-0 top-0 h-full w-2 cursor-col-resize"></div>
        </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr class="hover:bg-violet-100">
          <% all_fields_with_types(@model).each do |field, field_type| %>
            <td class="border px-4 py-3">
              <% if field == @model.column_names.second %>
                <%= component "UI/link", record[field], admin_edit_path(model: @model_name, id: record.id), class: "text-violet-700 underline" %>
              <% else %>
                <%= record[field] %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="mx-auto my-8">
  <%== pagy_nav @pagy %>
</div>

app/views/admin/crud/new.html.erb
<%= render "form", record: @record, model_name: @model_name %>

app/views/admin/dashboards/index.html.erb
<%= component "UI/text", "Hello World!" %>

app/views/admin/dashboards/show.html.erb
<%= component "UI/Text", "Dashboard" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dashboard" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= component "admin/screen" do |screen| %>
      <% screen.with_sidebar_item "Dashboard", "Dashboard page for information", admin_root_path, "fa-solid fa-dashboard text-teal-500", test_sub_path: false %>
      <% Rails.application.config.admin_registered_models.each do |registered_model| %>
      <% resource_name = registered_model[:model].underscore.capitalize %>
        <% screen.with_sidebar_item resource_name.pluralize, "#{resource_name.pluralize} admin page, lists all records.", admin_index_path(model: resource_name), "fa-solid fa-users text-amber-500" %>
      <% end %>
      
      <div style="grid-area: body;">
        <%= yield %>
      </div>

      <div style="grid-area: left;"></div>
      <div style="grid-area: right;"></div>
      
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dashboard" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>